service: pragmatic-clean-api
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  httpApi:
    payload: '2.0'
    metrics: true

custom:
  serverless-offline:
    httpPort: 3005

functions:
  main:
    handler: dist/infra/main.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          method: ANY
          path: /{proxy+}
